{
 "title": "Truss User Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(taco_cluster)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(truss:device:xpu_power{taco_cluster=~\"$cluster\"},hostname)"
    }
   },
   {
    "name": "isvc",
    "label": "Inference Service",
    "query": {
     "query": "label_values(vllm:generation_tokens_total,model_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{container='kube-prometheus-stack', namespace=~'truss-system|truss',  taco_cluster=~\"${cluster}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(truss:device:xpu_usage{taco_cluster=~\"$cluster\"}) by (device_type)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "GeneratedTokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(truss:service:generated_token_count{taco_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "increase"
    },
    {
     "expr": "sum(truss:service:generated_token_count{taco_cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "xPUs per each cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "count (truss:device:xpu_usage{taco_cluster=~\"$cluster\"}) by(taco_cluster, device_type) ",
     "legendFormat": "GPUs"
    },
    {
     "expr": "count (truss:device:xpu_usage{taco_cluster=~\"$cluster\", exported_pod=''}) by(taco_cluster, device_type) ",
     "legendFormat": "AvailableGPUs"
    },
    {
     "expr": "sum (truss:device:xpu_mem_total{taco_cluster=~\"$cluster\"}) by(taco_cluster, device_type) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vllm:generation_tokens_total{taco_cluster=~\"$cluster\"}) by (taco_cluster, device_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (truss:device:xpu_mem_total{taco_cluster=~\"$cluster\", exported_pod=''}) by(taco_cluster, device_type) ",
     "legendFormat": "AvailableGPUs"
    }
   ]
  },
  {
   "title": "PrefilledTokens",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(truss:service:prefilled_token_count{taco_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "increase"
    },
    {
     "expr": "sum(truss:service:prefilled_token_count{taco_cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Inference Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(taco_cluster, model_name) (truss:service:generated_token_count{taco_cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(truss:service:e2e_latency_seconds_sum{taco_cluster=~\"$cluster\"}[$__range]) / increase(truss:service:e2e_latency_seconds_count{taco_cluster=~\"$cluster\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(truss:service:ttft_seconds_sum{taco_cluster=~\"$cluster\"}[$__range]) / increase(truss:service:ttft_seconds_count{taco_cluster=~\"$cluster\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(truss:service:tpot_seconds_sum{taco_cluster=~\"$cluster\"}[$__range]) / increase(truss:service:tpot_seconds_count{taco_cluster=~\"$cluster\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inference Service [ $isvc ]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "isvc" },
  {
   "title": "Latency ($isvc)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(truss:service:e2e_latency_seconds_bucket{model_name=~\"$isvc\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TTFT($isvc)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "increase(truss:service:ttft_seconds_bucket{model_name=~\"$isvc\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TPOT($isvc)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "increase(truss:service:tpot_seconds_bucket{model_name=~\"$isvc\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "xPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  truss:device:xpu_usage\n  and on(exported_namespace, exported_pod)\n  label_replace(\n    label_replace(\n      vllm:generation_tokens_created{model_name=\"$isvc\"},\n      \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"\n    ),\n    \"exported_pod\", \"$1\", \"pod\", \"(.*)\"\n  )\n) by (device_type)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "xPU",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "group by(taco_cluster, hostname, uuid, exported_namespace, exported_pod, card, model_name, pci_bus_id) (truss:device:xpu_power) and on(exported_namespace, exported_pod) label_replace(label_replace(vllm:generation_tokens_total{model_name=\"$isvc\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"), \"exported_pod\", \"$1\", \"pod\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(vllm:generation_tokens_total{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}) by (taco_cluster, namespace, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg( increase(vllm:e2e_request_latency_seconds_sum{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range]) /\nincrease(vllm:e2e_request_latency_seconds_count{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg( increase(vllm:time_to_first_token_seconds_sum{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range]) /\nincrease(vllm:time_to_first_token_seconds_count{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg( increase(vllm:time_per_output_token_seconds_sum{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range]) /\nincrease(vllm:time_per_output_token_seconds_count{taco_cluster=~\"$cluster\", model_name=~\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Status [ $cluster ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "xPUs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 161 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(truss:device:xpu_usage{taco_cluster=~\"$cluster\"}) by (device_type)",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "xPU Memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 2, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(truss:device:xpu_mem_total{taco_cluster=\"$cluster\"}) by (device_type)",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "xPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 5, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(truss:device:xpu_usage{taco_cluster=~\"$cluster\"}) by (taco_cluster, device_type)",
       "legendFormat": "{{device_type}} Spot"
      },
      {
       "expr": "avg by(taco_cluster, device_type) (avg_over_time(truss:device:xpu_usage{taco_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "xPU Power Consumption",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 8, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(truss:device:xpu_power{taco_cluster=~\"$cluster\"}) by (taco_cluster, device_type)",
       "legendFormat": "{{ device_type }}"
      }
     ]
    },
    {
     "title": "xPU Temp",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 11, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(truss:device:xpu_temp{taco_cluster=~\"$cluster\"}) by (taco_cluster, device_type)",
       "legendFormat": "{{device_type}}"
      }
     ]
    },
    {
     "title": "GeneratedTokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 161 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(truss:service:generated_token_count{taco_cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "increase"
      },
      {
       "expr": "sum(truss:service:generated_token_count{taco_cluster=\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 19, "y": 161 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_node_name{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System CPU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{taco_cluster=\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "PrefilledTokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 165 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(truss:service:prefilled_token_count{taco_cluster=~\"$cluster\"}[$__range]))",
       "legendFormat": "increase"
      },
      {
       "expr": "sum(truss:service:prefilled_token_count{taco_cluster=~\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Inference Service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 19, "y": 165 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(vllm:cache_config_info{taco_cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "System RAM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{taco_cluster=\"$cluster\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Inference Services",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 169 },
     "targets": [
      {
       "expr": "sum by(taco_cluster, model_name) (truss:service:generated_token_count{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(truss:service:e2e_latency_seconds_sum{taco_cluster=\"$cluster\"}[$__range]) / increase(truss:service:e2e_latency_seconds_count{taco_cluster=\"$cluster\"}[$__range])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(truss:service:ttft_seconds_sum{taco_cluster=\"$cluster\"}[$__range]) / increase(truss:service:ttft_seconds_count{taco_cluster=\"$cluster\"}[$__range])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(truss:service:tpot_seconds_sum{taco_cluster=\"$cluster\"}[$__range]) / increase(truss:service:tpot_seconds_count{taco_cluster=\"$cluster\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPUs",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 175 },
     "targets": [
      {
       "expr": "avg by (taco_cluster, card, hostname, device, device_type, exported_pod, pci_bus_id, uuid) (truss:device:xpu_temp{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (taco_cluster, card, hostname, device, device_type, exported_pod, pci_bus_id, uuid) (truss:device:xpu_usage{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (taco_cluster, card, hostname, device, device_type, exported_pod, pci_bus_id, uuid) (truss:device:xpu_power{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (taco_cluster, card, hostname, device, device_type, exported_pod, pci_bus_id, uuid) (truss:device:xpu_mem_usage{taco_cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "xPU Utilization [ cluster $cluster ]",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "group by(hostname, device, device_type) (truss:device:xpu_usage{taco_cluster=\"$cluster\"})",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Temp.  [ cluster $cluster ]",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 181 },
     "targets": [
      {
       "expr": "group by(hostname, device, device_type) (truss:device:xpu_temp{taco_cluster=\"$cluster\"})",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Memory Utilization  [ cluster $cluster ]",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 181 },
     "targets": [
      {
       "expr": "group by(hostname, device, device_type) (truss:device:xpu_mem_usage{taco_cluster=\"$cluster\"})",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Utilization [ cluster $cluster ]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_usage{taco_cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Temp.  [ cluster $cluster ]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_temp{taco_cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Memory Utilization  [ cluster $cluster ]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_mem_usage{taco_cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Power Consumption [ cluster $cluster ]",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_power{taco_cluster=\"$cluster\"}",
       "legendFormat": "{{hostname}}/{{device_type}}/{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "xPUs of $hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "hostname",
   "collapsed": true,
   "panels": [
    {
     "title": "xPU Utilization",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 664 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_usage{taco_cluster=~\"$cluster\", hostname=\"$hostname\"}",
       "legendFormat": "RBLN/{{card}}"
      }
     ]
    },
    {
     "title": "xPU Temp.",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 664 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_temp{taco_cluster=~\"$cluster\", hostname=\"$hostname\"}",
       "legendFormat": "RBLN/{{card}}"
      }
     ]
    },
    {
     "title": "xPU Memory Utilization ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 664 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_mem_usage{taco_cluster=~\"$cluster\", hostname=\"$hostname\"}",
       "legendFormat": "RBLN/{{card}}"
      }
     ]
    },
    {
     "title": "xPU Memory Temp. (GPU only)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 664 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_mem_temp{taco_cluster=\"$cluster\", hostname=\"$hostname\"}",
       "legendFormat": "GPU/{{device}}"
      }
     ]
    },
    {
     "title": "xPU Power Consumption",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 664 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "truss:device:xpu_power{taco_cluster=~\"$cluster\", hostname=\"$hostname\"}",
       "legendFormat": "RBLN/{{card}}"
      }
     ]
    }
   ]
  }
 ]
}