{
 "title": "Truss-Inference-Service",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(truss:service:generated_token_count,taco_cluster)"
    }
   },
   {
    "name": "isvc",
    "label": "model_name",
    "query": {
     "query": "label_values(truss:service:generated_token_count{taco_cluster=\"$cluster\"},model_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(vllm:generation_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"},pod)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{taco_cluster=\"$cluster\", pod=~\"$pod\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "성능", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "지연시간 (avg, s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(truss:service:e2e_latency_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval]) / rate(truss:service:e2e_latency_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "increase(truss:service:e2e_latency_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TTFT(avg, s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(truss:service:ttft_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval]) / rate(truss:service:ttft_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "increase(truss:service:ttft_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TPOT(avg, s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(truss:service:tpot_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval]) / rate(truss:service:tpot_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "increase(truss:service:tpot_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(truss:service:e2e_latency_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(truss:service:ttft_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(truss:service:tpot_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Token 생성", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prefill(1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(truss:service:prefilled_token_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(truss:service:request_prefilled_tokens{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(truss:service:request_generated_tokens{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate(1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(truss:service:generated_token_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "xPU 사용정보", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "xPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truss:device:xpu_usage{taco_cluster=\"$cluster\", exported_pod=~\"$pod\"}",
     "legendFormat": "{{hostname}} {{device}}"
    }
   ]
  },
  {
   "title": "xPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truss:device:xpu_mem_usage{taco_cluster=\"$cluster\", exported_pod=~\"$pod\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "MAX. Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(truss:device:xpu_temp{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "MAX. mem. Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(truss:device:xpu_mem_temp{exported_pod=~\"${pod}\", taco_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "xPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(truss:device:xpu_power{exported_pod=~\"${pod}\", taco_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "POD별 비교",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services Pods",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 361 },
     "targets": [
      {
       "expr": "sum(vllm:generation_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"}) by (taco_cluster, namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg( increase(vllm:e2e_request_latency_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range]) /\nincrease(vllm:e2e_request_latency_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg( increase(vllm:time_to_first_token_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range]) /\nincrease(vllm:time_to_first_token_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg( increase(vllm:time_per_output_token_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range]) /\nincrease(vllm:time_per_output_token_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range])) by (taco_cluster, namespace, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed Tokens",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 367 },
     "targets": [
      {
       "expr": "increase(vllm:prompt_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range])",
       "legendFormat": "{{pod}}/prefilled"
      },
      {
       "expr": "increase(vllm:generation_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__range])",
       "legendFormat": "{{pod}}/generated"
      }
     ]
    },
    {
     "title": "Total Processed Tokens",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 5, "y": 367 },
     "targets": [
      {
       "expr": "vllm:prompt_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"}",
       "legendFormat": "{{pod}}/prefilled"
      },
      {
       "expr": "vllm:generation_tokens_total{taco_cluster=\"$cluster\", model_name=\"$isvc\"}",
       "legendFormat": "{{pod}}/generated"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 9, "y": 367 },
     "targets": [
      {
       "expr": "rate(vllm:e2e_request_latency_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
       "legendFormat": "{{pod}}/avg"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(vllm:e2e_request_latency_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}/95%"
      }
     ]
    },
    {
     "title": "TTFT",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 367 },
     "targets": [
      {
       "expr": "rate(vllm:time_to_first_token_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
       "legendFormat": "{{pod}}/avg"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(vllm:time_to_first_token_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}/95%"
      }
     ]
    },
    {
     "title": "TPOT",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 367 },
     "targets": [
      {
       "expr": "rate(vllm:time_per_output_token_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])",
       "legendFormat": "{{pod}}/avg"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(vllm:time_per_output_token_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\"}[$__rate_interval])))",
       "legendFormat": "{{pod}}/95%"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod별 상세 ($pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "increase(vllm:e2e_request_latency_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TTFT",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 23 },
     "targets": [
      {
       "expr": "increase(vllm:time_to_first_token_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TPOT",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "increase(vllm:time_per_output_token_seconds_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "완료조건",
     "type": "piechart",
     "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(finished_reason) (increase(vllm:request_success_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "xPU 점유비율",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(vllm:request_prefill_time_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "Prefill"
      },
      {
       "expr": "rate(vllm:request_decode_time_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "Decode"
      }
     ]
    },
    {
     "title": "Scheduler State",
     "type": "piechart",
     "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vllm:num_requests_running{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "vllm:num_requests_swapped{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}",
       "legendFormat": "Swapped"
      },
      {
       "expr": "vllm:num_requests_waiting{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}",
       "legendFormat": "Waiting"
      }
     ]
    },
    {
     "title": "GPU Cache Usage (%)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vllm:gpu_cache_usage_perc{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}",
       "legendFormat": "GPU"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio (%)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 2, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(vllm:prefix_cache_hits_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__range])/increase(vllm:prefix_cache_queries_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__range])",
       "legendFormat": "Range"
      },
      {
       "expr": "vllm:prefix_cache_hits_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}/vllm:prefix_cache_queries_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}",
       "legendFormat": "Lifetime"
      }
     ]
    },
    {
     "title": "Cache offload",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 5, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(vllm:num_preemptions_total{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Configuration",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 7, "y": 32 },
     "targets": [
      {
       "expr": "vllm:cache_config_info{taco_cluster=\"$cluster\", pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(vllm:request_queue_time_seconds_sum{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Prompt Length",
     "type": "heatmap",
     "description": "Heatmap of request prompt length",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 35 },
     "targets": [
      {
       "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Generation Length",
     "type": "heatmap",
     "description": "Heatmap of request generation length",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 35 },
     "targets": [
      {
       "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{taco_cluster=\"$cluster\", model_name=\"$isvc\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Avg. Temp",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "GPU Power Total",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 5, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(Hostname, gpu)  (DCGM_FI_DEV_FB_USED{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"}) / sum by(Hostname, gpu) (DCGM_FI_DEV_FB_USED{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"} + DCGM_FI_DEV_FB_FREE{exported_pod=\"${pod}\", taco_cluster=\"$cluster\"})",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "xPU",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "group by(taco_cluster, hostname, uuid, exported_namespace, exported_pod, card, model_name, pci_bus_id) (truss:device:xpu_power) and on(exported_namespace, exported_pod) label_replace(label_replace(vllm:generation_tokens_total{model_name=\"$isvc\"}, \"exported_namespace\", \"$1\", \"namespace\", \"(.*)\"), \"exported_pod\", \"$1\", \"pod\", \"(.*)\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$pod\", taco_cluster=\"$cluster\", container=~\"engine|vllm|server\", service=\"truss-mon-kubelet\"}[1m]) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{ pod=~\"$pod\", taco_cluster=\"$cluster\", container=~\"engine|vllm|server\", service=\"truss-mon-kubelet\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}