targetClusterName: cluster6
labels:
  app.kubernetes.io/name: truss-worker-provisioner
  app.kubernetes.io/version: 1.0.0
  app.kubernetes.io/managed-by: truss

lmaProvisioner:
  enabled: true
  image:
    repository: siim/kubectl-helm-git-yq
    tag: kv1.30.1-hv3.18.2-yv4.45.1
    pullPolicy: IfNotPresent
  backoffLimit: 3
  objstore:
    type: s3
    config:
      access_key: taco
      bucket: truss-thanos
      endpoint: 127.0.0.1:30003
      insecure: true
      secret_key: password
  podMonitor:
  - name: kubeai-models-pod-monitor
    endpoint:
    - port: http
      path: /metrics
      interval: 15s
    selector:
      matchLabels:
        app.kubernetes.io/managed-by: truss
        app.kubernetes.io/name: engine
    targetNamespaces:
      - kubeai
  xpuSupport:
    dcgm:
      enabled: false
    rbln:
      enabled: false
  component:
    prometheus:
      repository: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 46.11.0
    dcgm-exporter:
      repository: https://nvidia.github.io/dcgm-exporter/helm-charts
      chart: dcgm-exporter
      version: 4.2.0