# docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 . -t siim/kubectl-helm-git-yq:kv1.30.1-hv3.18.2-yv4.45.1 --push
# docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 . -t siim/kubectl-helm-git-yq:kv1.29.7-hv3.17.1-yv4.45.1 --push
FROM alpine:3.20

# 환경 변수에 TARGETARCH 추가
ARG TARGETARCH

# 필요한 환경 변수 정의 (버전 고정 가능)
#ENV KUBECTL_VERSION=v1.30.1
#ENV HELM_VERSION=v3.18.2
ENV KUBECTL_VERSION=v1.29.7
ENV HELM_VERSION=v3.17.1
ENV YQ_VERSION=v4.45.1

RUN apk add --no-cache curl git bash jq ca-certificates \
    # kubectl 다운로드 시 TARGETARCH 사용
    && curl -L "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl" -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    # Helm 다운로드 URL 수정
    && curl -LO "https://get.helm.sh/helm-${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" \
    # yq 다운로드 URL 수정
    && tar -xzvf ./helm-${HELM_VERSION}-linux-*.tar.gz \
    && mv linux-*/helm /usr/local/bin/helm \
    && rm -rf helm-${HELM_VERSION}-linux-*.tar.gz linux-* \
    && curl -Lo /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" \
    && chmod +x /usr/local/bin/yq

# # 기본 쉘 지정(선택)
# SHELL ["/bin/bash", "-c"]

# # 기본 작업 디렉터리
# WORKDIR /work

# CMD [ "sh" ]
