name: Release Charts

on:
  push:
    branches:
      - main  # main 브랜치에 푸시되거나 PR이 머지될 때 실행

jobs:
  release:
    # GitHub Pages 배포를 위한 권한 설정
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0 # 필요에 따라 최신 버전으로 변경 가능

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
