{{- if .Values.lmaProvisioner.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-lma-provisioner-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key  }}: {{ $value }}
  {{- end}}
spec:
  backoffLimit: {{ .Values.lmaProvisioner.backoffLimit }}
  template:
    metadata:
      labels:
      {{- range $key, $value := .Values.labels }}
        {{ $key  }}: {{ $value }}
      {{- end}}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      restartPolicy: OnFailure
      containers:
      - name: lma-remover
        image: {{ .Values.lmaProvisioner.image.repository }}:{{ .Values.lmaProvisioner.image.tag }}
        command: ["/cm/remove.sh"]
        volumeMounts:
        - name: cm-volume
          mountPath: /cm
      volumes:
      - name: cm-volume
        configMap:
          name: {{ .Release.Name }}-lma-provisioner
          defaultMode: 0755
{{- end }}