{{- range $worker := .Values.workerProvisioner.clusters }}
{{- if $worker.kubeconfig.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $worker.kubeconfig.secretName }}
type: Opaque
data:
  config: {{ $worker.kubeconfig.config | toYaml | b64enc }}
---
{{- end }}
{{- end }}